In [1]:
import jax 
import flax
import optax
import numpy as np
from flax import nnx, linen as ln
from jax import numpy as jnp

In [7]:
k = jnp.array([[4.0, 5.0], [5.0, 6.0]])
v = jnp.array([[1.0, 2.0], [3.0, 4.0]])

k, v

(Array([[4., 5.],
        [5., 6.]], dtype=float32),
 Array([[1., 2.],
        [3., 4.]], dtype=float32))

In [8]:
k.shape, v.shape

((2, 2), (2, 2))

In [11]:
q = jnp.dot(k, v)

q

Array([[19., 28.],
       [23., 34.]], dtype=float32)